[package]
authors = ["Fastly <slack #executed>"]
edition = "2018"
name = "prometheus-utils"
publish = false
version = "0.1.0"

[dependencies]
lazy_static = "1.4.0"
paste = "^1.0.4"
pin-project = "1.0.0"
prometheus = "0.11.0"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["full"] }
